language: c
dist: bionic

os:
- linux
- osx

arch:
  - amd64
  - ppc64le

compiler:
- gcc
- clang

matrix:
   exclude:
      - os: osx
        arch: ppc64le

addons:
  apt:
    packages:
    - libcairo2-dev
    - unicode-data
    - libglib2.0-dev
    - pkg-config
    - libfreetype6-dev
    - libpango1.0-dev
    - gettext
    - cmake
  homebrew:
    packages:
    - cmake
    - pkg-config
    - gettext
    - cairo
    - pango
    - fontconfig
    - freetype
    - glib
    update: true

before_script:
- '
if [ $TRAVIS_OS_NAME = osx ]; then
  export CMAKE_PREFIX_PATH="/usr/local/opt/gettext" ;
  export UNICODE_BLOCKS_ARG=-DCHECK_UNICODE_CERT=OFF ;
else
  export UNICODE_BLOCKS_ARG=-DUNICODE_BLOCKS=/usr/share/unicode/Blocks.txt ;
fi
'

before_install:
        - if [ "$TRAVIS_ARCH" = "ppc64le" ]; then sudo apt-get update && sudo apt-get install make gcc g++ wget libncurses5-dev -y && wget https://cmake.org/files/v3.18/cmake-3.18.4.tar.gz && tar -xzvf cmake-3.18.4.tar.gz && cd cmake-3.18.4 && ./bootstrap && make && make install && cd .. && rm -rf cmake-3.18.4.tar.gz && apt-get purge --auto-remove wget make gcc g++ -y ; export PATH=export PATH=/fntsample/cmake-3.18.4/bin/cmake/bin:${PATH}; cmake --version ; fi
script:
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Release ${UNICODE_BLOCKS_ARG} ..
- make VERBOSE=1
- ./src/fntsample --help
- make package
- tar tzf fntsample-*.tar.gz
